import { writeFileSync } from "node:fs";
import { generateAffidavitPdf } from "../lib/affidavitPdf";
import type { Job } from "@workspace/db";

const servedAt = new Date("2026-05-09T15:42:00-07:00");
const generatedAt = new Date("2026-05-09T15:50:00-07:00");

const job: Job = {
  id: 10472,
  requesterUserId: "user_demo",
  status: "served",
  documentType: "Summons & Complaint",
  recipientName: "Marcus T. Holloway",
  recipientAddress: "2418 Sahara Vista Court",
  recipientCity: "Las Vegas",
  recipientState: "NV",
  recipientZip: "89117",
  caseNumber: "A-26-847291-C",
  deptNumber: "14",
  matterName: "Apex Holdings LLC v. Holloway",
  requesterName: "Carla Reyes, Esq.",
  requesterEmail: "creyes@apexlegal.example",
  requesterPhone: "702-555-0142",
  courtName: "Eighth Judicial District Court, Clark County, Nevada",
  petitioner: "APEX HOLDINGS, LLC",
  respondent: "MARCUS T. HOLLOWAY",
  notes: null,
  documentHandling: "pickup",
  pickupAddress: "400 S Rampart Blvd, Ste 200",
  pickupCity: "Las Vegas",
  pickupState: "NV",
  pickupZip: "89145",
  pickupContactName: "Apex Legal Front Desk",
  pickupContactPhone: "702-555-0100",
  clientId: null,
  serverId: 42,
  assignedAt: new Date("2026-05-07T09:12:00-07:00"),
  pickedUpAt: new Date("2026-05-07T11:30:00-07:00"),
  servedAt,
  enRouteAt: new Date("2026-05-07T18:05:00-07:00"),
  releaseReason: null,
  releasedAt: null,
  gpsLat: 36.13682,
  gpsLng: -115.27419,
  proofPhotoUrl: null,
  proofPdfUrl: null,
  noticeOfMailPdfUrl: null,
  signatureTypedName: "Daniel Cruz",
  signatureImageUrl: null,
  payoutEligibleAt: servedAt,
  platformRef: "SVD-26-10472",
  serviceType: "standard",
  grossCents: 7500,
  platformFeeCents: 1500,
  serverPayoutCents: 6000,
  pricingTier: "public",
  requiresLicensedServer: true,
  createdAt: new Date("2026-05-07T08:55:00-07:00"),
  updatedAt: servedAt,
};

const buf = await generateAffidavitPdf({
  job,
  server: {
    name: "Daniel Cruz",
    email: "support@servedapp.co",
    phone: "775-655-3933",
    licenseNumber: "PILB-R-2418",
    licenseState: "NV",
    licenseCounty: "Clark",
    businessAddress: "732 S 6TH ST #6750, LAS VEGAS, NV 89101",
    isLicensedNvServer: true,
    serverType: "licensed_nv",
  },
  signatureTypedName: "Daniel Cruz",
  servedAt,
  generatedAt,
  attempts: [
    {
      outcome: "unable",
      attemptedAt: new Date("2026-05-07T18:42:00-07:00"),
      notes: "Knocked, rang bell. No answer. Vehicle (silver Toyota Camry, NV plate 887•KCJ) in driveway. Lights off.",
      gpsLat: 36.13684,
      gpsLng: -115.27415,
      serviceAddress: "2418 Sahara Vista Court",
      serviceCity: "Las Vegas",
      serviceState: "NV",
      serviceZip: "89117",
    },
    {
      outcome: "unable",
      attemptedAt: new Date("2026-05-08T07:15:00-07:00"),
      notes: "Lights on inside, voices audible. Knocked twice. No response after 4 minutes.",
      gpsLat: 36.13681,
      gpsLng: -115.27418,
      serviceAddress: "2418 Sahara Vista Court",
      serviceCity: "Las Vegas",
      serviceState: "NV",
      serviceZip: "89117",
    },
    {
      outcome: "personal",
      attemptedAt: servedAt,
      notes: "Subject answered the door. Confirmed identity verbally and visually matched DMV photo.",
      gpsLat: 36.13682,
      gpsLng: -115.27419,
      serviceAddress: "2418 Sahara Vista Court",
      serviceCity: "Las Vegas",
      serviceState: "NV",
      serviceZip: "89117",
    },
  ],
  completingAttempt: {
    outcome: "personal",
    attemptedAt: servedAt,
    serviceAddress: "2418 Sahara Vista Court",
    serviceCity: "Las Vegas",
    serviceState: "NV",
    serviceZip: "89117",
    methodNarrative:
      "Hand-delivered Summons and Complaint to MARCUS T. HOLLOWAY at the front entrance of his residence at 2418 Sahara Vista Court, Las Vegas, NV 89117.",
    recipientDescription: "White male, brown hair, approx. 6'0\", ~190 lbs, beard, wearing gray t-shirt and jeans.",
    recipientAgeEstimate: "35-44",
    recipientGender: "Male",
    recipientHeight: "6'0\"",
    recipientWeight: "190 lbs",
    recipientIdentifyingFeatures: "Short beard; tattoo on right forearm.",
    identityMethod: "verbal",
    gpsProvider: "gps",
  },
  documentsServed: [
    { title: "Summons", documentType: "Summons" },
    { title: "Complaint", documentType: "Complaint" },
    { title: "Civil Cover Sheet", documentType: "Civil Cover Sheet" },
  ],
  requesterName: "Carla Reyes, Esq.",
  requesterEmail: "creyes@apexlegal.example",
  requesterPhone: "702-555-0142",
  client: {
    firmName: "Apex Legal, LLC",
    contactName: "Carla Reyes, Esq.",
    email: "creyes@apexlegal.example",
    phone: "702-555-0142",
  },
  legalEntityName: "SERVED.",
  legalBusinessAddress: "732 S 6TH ST #6750, LAS VEGAS, NV 89101",
  nevadaDeclaration:
    "I declare under penalty of perjury under the law of the State of Nevada that the foregoing is true and correct. (NRS 53.045)",
});

const out = process.argv[2] ?? "/tmp/sample-affidavit.pdf";
writeFileSync(out, buf);
console.log(`Wrote ${buf.length} bytes to ${out}`);
